#!/usr/bin/env bash
set -eu -o pipefail

die() {
    local exitcode=$1
    echo 2>&1 ERROR: "$@"
    exit $exitcode
}

basedir=$(cd "$(dirname "$0")" && pwd -P)

cd "$basedir"
. ./activate
pytest -q "$@"

out="$basedir/.build/tftd.out"


python tftd.py > "$out" || die 1 'FAILED: bad exit'
[[ $(wc -l <$out) -ge 1 ]] || die 1 'FAILED: bad output'

echo OK
