#!/usr/bin/env bash
set -eu -o pipefail

basedir=$(cd "$(dirname "$0")" && pwd -P)

cd "$basedir"
. ./activate
pytest -q "$@"

out="$basedir/.build/tftd.out"

python tftd.py > "$out" || die 1 'FAILED: bad exit'
grep -q 'A broad mind lacks focus' "$out" 2>&1 || die 1 'FAILED: bad output'

echo OK
